# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
