# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20180827_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
