# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20180827_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
