# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_cash_back'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cash_back',
            new_name='checkout',
        ),
    ]
