# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20181023_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.IntegerField(choices=[(0, '\u062f\u0631\u062e\u0648\u0627\u0633\u062a \u062a\u0633\u0648\u06cc\u0647 \u062d\u0633\u0627\u0628 \u0627\u0631\u0633\u0627\u0644 \u0634\u062f\u0647'), (1, '\u062a\u0633\u0648\u06cc\u0647 \u062d\u0633\u0627\u0628 \u062f\u0631 \u062d\u0627\u0644 \u0627\u0646\u062c\u0627\u0645'), (2, '\u062a\u0633\u0648\u06cc\u0647 \u062d\u0633\u0627\u0628 \u0627\u0646\u062c\u0627\u0645 \u0634\u062f\u0647')], default=0),
        ),
    ]
