# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_num',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
