# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('shop_type', models.IntegerField(choices=[(0, '\u06a9\u0627\u0641\u06cc\u200c\u0634\u0627\u067e'), (1, '\u0633\u0631\u06af\u0631\u0645\u06cc'), (2, '\u0631\u0633\u062a\u0648\u0631\u0627\u0646')])),
            ],
        ),
    ]
