# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20181021_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_type',
            new_name='category',
        ),
    ]
