# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20181021_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.IntegerField(choices=[('\u06a9\u0627\u0641\u06cc_\u0634\u0627\u067e', '\u06a9\u0627\u0641\u06cc_\u0634\u0627\u067e'), ('\u0633\u0631\u06af\u0631\u0645\u06cc', '\u0633\u0631\u06af\u0631\u0645\u06cc'), ('\u0631\u0633\u062a\u0648\u0631\u0627\u0646', '\u0631\u0633\u062a\u0648\u0631\u0627\u0646')]),
        ),
    ]
