# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20181022_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwnerPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.IntegerField(choices=[(0, '\u06a9\u0627\u0641\u06cc\u200c\u0634\u0627\u067e'), (1, '\u0633\u0631\u06af\u0631\u0645\u06cc'), (2, '\u0631\u0633\u062a\u0648\u0631\u0627\u0646')]),
        ),
        migrations.AddField(
            model_name='shopownerphonenumber',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
    ]
